# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: Marc Bielas Website
description: > # this means to ignore newlines until "baseurl:"
  A collection of my projects and writings.
name: Marc Bielas
url: "http://www.marcbielas.com" 
twitter_username: marcbielas
github_username:  marcbielas
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
gems:
  - jekyll-feed
    - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock